# Site settings
name: Sam Liao
email: liaomaos@msu.edu
#canonical_url: https://edwinexemplar.com
keywords: "Software Developement, Python, C++, Machine Learning, PHP, HTML/CSS, Agile Programming"
skills: "Computer Science Student Michigan State University"
baseurl:

social:
  - title: linkedin
    url: 
  - title: instagram
    url:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
